version: v0.1

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 8080
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider: openai
    model: gpt-4o

system_prompt: |
  You are a helpful assistant.

prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: Looks like you're curious about my abilities, but I can only provide assistance for currency exchange.

prompt_targets:
  - name: currency_exchange
    description: Get currency exchange rate from USD to other currencies
    parameters:
      - name: currency_symbol
        description: the currency that needs conversion
        required: true
        type: str
        in_path: true
    endpoint:
      name: frankfurt_api
      path: /v1/latest?base=USD&symbols={currency_symbol}
    system_prompt: |
      You are a helpful assistant. Show me the currency symbol you want to convert from USD.


  - name: get_supported_currencies
    description: Get list of supported currencies for conversion
    endpoint:
      name: agenti_api
      path: /api/v1/currencies

endpoints:
  agenti_api:
    endpoint: agenti:8000
    protocol: http
  frankfurt_api:
      endpoint: api.frankfurter.dev
      protocol: https