services:
  archgw:
    image: docker.io/katanemo/archgw:latest
    ports:
      - "8080:8080"
      - "12000:12000"
    volumes:
      - ./arch_config.yaml:/app/arch_config.yaml
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - MODEL_SERVER_PORT=${MODEL_SERVER_PORT:-51001} #confirm why it fails without this
    networks:
      - bluebell

  agenti:
    image: agenti:latest #built using `make build:docker` command
    networks:
      - bluebell

networks:
  bluebell:
